// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-notes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_notes_default = defineTool({
  name: "list_notes",
  title: "List notes",
  description: "List published study notes from A Help Deck, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of notes to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("notes").select("id,title,body,tags,file_url,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-notes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_notes_default = defineTool2({
  name: "search_notes",
  title: "Search notes",
  description: "Search study notes by title or body text.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Text to search for in note titles and bodies."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const escaped = query.replace(/[%_,]/g, (m) => `\\${m}`);
    const { data, error } = await supabase.from("notes").select("id,title,body,tags,file_url,created_at").or(`title.ilike.%${escaped}%,body.ilike.%${escaped}%`).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_announcements_default = defineTool3({
  name: "list_announcements",
  title: "List announcements",
  description: "List recent admin announcements/broadcasts from A Help Deck.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max announcements (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("broadcasts").select("id,title,body,url,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "a-help-deck-mcp",
  title: "A Help Deck",
  version: "0.1.0",
  instructions: "Tools for A Help Deck \u2014 a student helper. Use `list_notes` and `search_notes` to browse published study notes, and `list_announcements` to fetch recent broadcasts.",
  tools: [list_notes_default, search_notes_default, list_announcements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
